-- =============================================================================
-- Migration v5 — Production Readiness (Run in Supabase Studio → SQL Editor)
-- Safe to re-run: every statement is idempotent.
-- =============================================================================

-- 1. Add client_id (UUID generated by the app) for idempotent sync upserts.
--    This prevents duplicate rows when the same entry is synced multiple times.

ALTER TABLE milk_collections ADD COLUMN IF NOT EXISTS client_id uuid;
ALTER TABLE payouts           ADD COLUMN IF NOT EXISTS client_id uuid;
ALTER TABLE ledger_entries    ADD COLUMN IF NOT EXISTS client_id uuid;
ALTER TABLE local_sales       ADD COLUMN IF NOT EXISTS client_id uuid;
ALTER TABLE union_sales       ADD COLUMN IF NOT EXISTS client_id uuid;

-- Unique constraints: (society_id, client_id) — a given client_id can only
-- appear once per society. Ignores NULLs (pre-existing rows without client_id).
CREATE UNIQUE INDEX IF NOT EXISTS uq_mc_client    ON milk_collections (society_id, client_id) WHERE client_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_po_client    ON payouts           (society_id, client_id) WHERE client_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_le_client    ON ledger_entries    (society_id, client_id) WHERE client_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_ls_client    ON local_sales       (society_id, client_id) WHERE client_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_us_client    ON union_sales       (society_id, client_id) WHERE client_id IS NOT NULL;

-- 2. Add updated_at column to data tables (for two-way sync).
--    members already has updated_at from schema.sql.

ALTER TABLE milk_collections ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();
ALTER TABLE payouts           ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();
ALTER TABLE ledger_entries    ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();
ALTER TABLE local_sales       ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();
ALTER TABLE union_sales       ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

-- 3. Auto-update trigger: set updated_at = now() on any UPDATE.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END; $$;

-- Apply the trigger to every data table (DROP first to make idempotent).
DROP TRIGGER IF EXISTS trg_members_updated          ON members;
DROP TRIGGER IF EXISTS trg_milk_collections_updated ON milk_collections;
DROP TRIGGER IF EXISTS trg_payouts_updated          ON payouts;
DROP TRIGGER IF EXISTS trg_ledger_entries_updated   ON ledger_entries;
DROP TRIGGER IF EXISTS trg_local_sales_updated      ON local_sales;
DROP TRIGGER IF EXISTS trg_union_sales_updated      ON union_sales;

CREATE TRIGGER trg_members_updated          BEFORE UPDATE ON members          FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_milk_collections_updated BEFORE UPDATE ON milk_collections FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_payouts_updated          BEFORE UPDATE ON payouts          FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_ledger_entries_updated   BEFORE UPDATE ON ledger_entries   FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_local_sales_updated      BEFORE UPDATE ON local_sales      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_union_sales_updated      BEFORE UPDATE ON union_sales      FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 4. Add milk_type to local_sales if missing (needed by the app's local sale form).
ALTER TABLE local_sales ADD COLUMN IF NOT EXISTS milk_type text DEFAULT 'mix';

-- 5. App config table (stores the UPI payee VPA for subscription payments).
CREATE TABLE IF NOT EXISTS app_config (
  id              int PRIMARY KEY DEFAULT 1,
  upi_vpa         text DEFAULT '7737115459@upi',
  upi_payee_name  text DEFAULT 'Neerja Milk Collection',
  updated_at      timestamptz DEFAULT now()
);

-- Seed a default row if none exists.
INSERT INTO app_config (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- RLS: anyone can read app_config, only super-admins can write.
ALTER TABLE app_config ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "read app_config" ON app_config;
CREATE POLICY "read app_config" ON app_config FOR SELECT USING (true);
DROP POLICY IF EXISTS "super admin app_config" ON app_config;
CREATE POLICY "super admin app_config" ON app_config FOR ALL USING (
  (SELECT is_super_admin FROM profiles WHERE id = auth.uid()) = true
) WITH CHECK (
  (SELECT is_super_admin FROM profiles WHERE id = auth.uid()) = true
);

-- Done! ✓
